### ISSUE TITLE
Gold lose on /bank withdraw 

### ISSUE THREAD

**Issue by haxbob12345** [ConfusedAlex/GoldEconomy#20]
When ever a player has more gold in there bank then what they can hold, the left over gold gets lost.

**Comment by ConfusedAlex** [comment]
Can confirm

**Comment by haxbob12345** [comment]
Is there any bug fix with this?

**Comment by ConfusedAlex** [comment]
> 



> Is there any bug fix with this?

Give me 1 minute

**Comment by haxbob12345** [comment]
Alright, take your time

**Comment by ConfusedAlex** [comment]
Updated version are up :)

Modrinth (recommended, please use): https://modrinth.com/plugin/thegoldeconomy/version/1.5.1
Spigot: https://www.spigotmc.org/resources/thegoldeconomy-1-18-1-19-simple-gold-based-economy.102242/

**Comment by ConfusedAlex** [comment]
Thanks for creating an Issue :)

It really motivates me to see that people are using my plugin

**Comment by haxbob12345** [comment]
Thank youu

**Comment by haxbob12345** [comment]
Oh another question

**Comment by haxbob12345** [comment]
Am I allowed to edit the plugin to fit the needs for my server?

**Comment by ConfusedAlex** [comment]
> Am I allowed to edit the plugin to fit the needs for my server?

Sure, it's open source. But if the Server is public, you need to publish your the changes you made.

**Comment by ConfusedAlex** [comment]
If the changes benefited everyone, you could even make a pull request so that your edits will be available for everyone

**Comment by haxbob12345** [comment]
How would I publish them?

**Comment by ConfusedAlex** [comment]
> 

GitHub would be the easiest. If you have more question, text me on discord.

**Comment by haxbob12345** [comment]
Ok! Thank you!

**Comment by ConfusedAlex** [comment]
https://discord.gg/Vp6GSGewry

**Comment by ConfusedAlex** [comment]
I would really love to talk with you about the changes you want to make. Maybe I can help :)

**Comment by haxbob12345** [comment]
The changes I want to make were to remove the implementation of gold nuggets to have the economy fully run on ingots and blocks which I've achieved. I did this since I ran a server using a different item based economy plugin but there was a glitch in it so I switched to this one since it didn't have that glitch
