### ISSUE TITLE
Turkish translate added.

### ISSUE THREAD

**Issue by yusufklncc** [ConfusedAlex/GoldEconomy#29]
[TheGoldEconomy-1.0.zip](https://github.com/ConfusedAlex/GoldEconomy/files/15457537/TheGoldEconomy-1.0.zip)
First i converted language .properties files to utf-8 and add turkish file. And added 

else if ("tr_TR".equals(configFile.getString("language"))) {
            Locale locale = new Locale("tr", "TR");
            bundle = ResourceBundle.getBundle("messages", locale);
        }
        
lines to TheGoldEconomy.java.

**Comment by ConfusedAlex** [comment]
Hey! First I am very thankful for your contribution. Would you mind forking this project and creating a pull request or just sending me the language file? Just using a jar you sent me is somewhat of a malware risk. If you need help just hit me up

**Comment by yusufklncc** [comment]
[GoldEconomy-master.zip](https://github.com/ConfusedAlex/GoldEconomy/files/15462142/GoldEconomy-master.zip)
Here is the source folder as I added it. Will that be enough?

**Comment by ConfusedAlex** [comment]
Yes, thanks for your contribution! I will update it soon

**Comment by ConfusedAlex** [comment]
I've updated the plugin

**Comment by yusufklncc** [comment]
Okey. Thank you for your work and this plugin. Have a nice day.
