### ISSUE TITLE
[SUGGESTION] Placeholders

### ISSUE THREAD

**Issue by chatillon7** [ConfusedAlex/GoldEconomy#30]
Could you add placeholders into your plugin? Something like: %thegoldeconomy_in_bank% & %thegoldeconomy_in_inventory%

**Comment by ConfusedAlex** [comment]
Next days are quite busy, but I can try next week

**Comment by ConfusedAlex** [comment]
Hey @chatillon7, placeholder support is now shipped with the new version 1.6.3 of TheGoldEconomy! You can download the new version on [Modrinth (preferred)](https://modrinth.com/plugin/thegoldeconomy/versions) or as usual on Spigot.
