### ISSUE TITLE
Error Logs when running basic commands

### ISSUE THREAD

**Issue by Zatiejo** [ConfusedAlex/GoldEconomy#31]
**DISCLAIMER: I am running this plugin on 1.21 paper, so feel free to take this bug submit with a grain of salt as just an update issue.**

1. There are few janky responses from the plugin when doing commands such as '/bank deposit (amount)' and '/bank withdraw (amount)'

- With '/bank deposit (amount)' It sends the classic contact an admin error message after the successful message when depositing an exact amount of gold. When depositing as '/bank deposit all' it doesn't show this message- nor shoots an error log in the console. As seen in this images below:
![thegoldeconomy2](https://github.com/ConfusedAlex/GoldEconomy/assets/61992533/193f04ac-1ab6-4825-8e2a-2648804fe0b0)
![thegoldeconomy4_deposit](https://github.com/ConfusedAlex/GoldEconomy/assets/61992533/9ea41737-b852-45a5-a9c6-c7da649bd23a)

- With '/bank withdraw (amount)' It's a bit more flimsy. The error message shows up for both specific amount and '/bank withdraw all' including the error messages in console. The difference being that withdrawing a specific amount doesn't put the specific amount within your inventory that you request, but just eats/gets rid of the amount you withdraw. In other words, withdrawing but not receiving. However, withdrawing all your gold at once DOES give you your gold back.
![thegoldeconomy3](https://github.com/ConfusedAlex/GoldEconomy/assets/61992533/ce1ba61b-ad67-435f-9e47-e901b07b5b8f)
![thegoldeconomy4](https://github.com/ConfusedAlex/GoldEconomy/assets/61992533/e4391463-6788-4245-8a94-cc9f18146c42)

2. The Plugin itself is almost usable, and doesn't start up with any error logs. It's just the previous two errors. Paying other players in gold works fine. Bank balance works just fine.
![thegoldeconomy`](https://github.com/ConfusedAlex/GoldEconomy/assets/61992533/664e4e05-ac25-452b-b95d-0bc9de536c20)
However, just in case you need it, here is also a list of plugins I use for my server:
![thegoldeconomy5](https://github.com/ConfusedAlex/GoldEconomy/assets/61992533/ad9ca94e-8f57-4685-ac37-a34a68faa9d4)

**If you need any more info I'll have to see what I can do. For now, this was all I was able to find and report.**

**Comment by ConfusedAlex** [comment]
Turns out, papermc handles some things a little bit differently than spigotmc. While in spigot creating an item with a negative amount, which was done in the plugin, will work, papermc threw an error telling us we can't create items with a negative amount. I just added some if statements and it's fixed now. Just download 1.6.2, preferably from [modrinth](https://modrinth.com/plugin/thegoldeconomy/version/1.6.2)
