### ISSUE TITLE
Implement own command system

### ISSUE THREAD

**Issue by ConfusedAlex** [ConfusedAlex/GoldEconomy#35]
Remove RedLib and implement own command system

**Comment by ConfusedAlex** [comment]
Maybe even use [ACF](https://github.com/aikar/commands). Seems to be better supported and developed and, if I read correctly, can handle both cases mentioned in the issues.

**Comment by ooonhkj** [comment]
However, the file will be reloaded after deletion

**Comment by ConfusedAlex** [comment]
> However, the file will be reloaded after deletion

I dont understand

**Comment by ooonhkj** [comment]
chinese



---Original---
From: ***@***.***&gt;
Date: Wed, Aug 7, 2024 03:07 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ConfusedAlex/GoldEconomy] Implement own command system (Issue#35)




  
However, the file will be reloaded after deletion
  
I dont understand

**Comment by ConfusedAlex** [comment]
Closed by using ACF now
