### ISSUE TITLE
Change the language of the game plugin

### ISSUE THREAD

**Issue by ooonhkj** [ConfusedAlex/GoldEconomy#40]
How do I set the language to a language other than English, I set my own language in the config file but it doesn't change in the game

**Comment by ConfusedAlex** [comment]
to which language did you set it in the config file?

**Comment by ooonhkj** [comment]
I set the Chinese




---Original---
From: ***@***.***&gt;
Date: Wed, Aug 7, 2024 02:50 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ConfusedAlex/GoldEconomy] Change the language of the game plugin(Issue #40)




 
to which language did you set it in the config file?

**Comment by ooonhkj** [comment]
When I found that Chinese could not be set, I tried to test other languages to see if only Chinese was problematic, and found that other languages could not be set, and the game would only be English




---Original---
From: ***@***.***&gt;
Date: Wed, Aug 7, 2024 02:50 AM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [ConfusedAlex/GoldEconomy] Change the language of the game plugin(Issue #40)




 
to which language did you set it in the config file?

**Comment by ConfusedAlex** [comment]
May you send me a copy of your config file, the plugin version you are using and the server (Bukkit, Spigot, PaperMC, Purpur) which you are using?

**Comment by ooonhkj** [comment]
The zip file I sent is the server I opened, I set the configuration file to Chinese is still English "插件服务器" English means plug-in server, thank you


扔向虚无
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "ConfusedAlex/GoldEconomy"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年8月8日(星期四) 凌晨3:05
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [ConfusedAlex/GoldEconomy] Change the language of the game plugin (Issue #40)





 
May you send me a copy of your config file, the plugin version you are using and the server (Bukkit, Spigot, PaperMC, Purpur) which you are using?
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;


从QQ邮箱发来的超大附件

插件服务器.zip (286.29M, 2024年09月07日 19:18 到期)进入下载页面：https://mail.qq.com/cgi-bin/ftnExs_download?k=7a62383669337ddfb69652b71265541e41160a5707525752145a5e01064856570b55150307545e1c08010f500c06555409550f04346b6683dcdec681caab97f7ce4c425f44655b&t=exs_ftn_download&code=9b864ef1

**Comment by ooonhkj** [comment]
I tested other languages that can't be changed to the corresponding language, including my native Chinese, can you see what the specific problem is, is there a problem with my language profile
