### ISSUE TITLE
Suggestion: Bank Balance Alias

### ISSUE THREAD

**Issue by Firav** [ConfusedAlex/GoldEconomy#43]
Create an alias to /bank balance to be /balance. Allows for ease of use for users coming from Essentials-based servers.

**Comment by ConfusedAlex** [comment]
I am currently working on this. Should be finished next week.

**Comment by Firav** [comment]
> I am currently working on this. Should be finished next week.

Oh sorry Alex, I didnt see this! I thought this was the comment you made on #44!
