### ISSUE TITLE
TheGoldEconomy withdraw amount says 0 but deposits work

### ISSUE THREAD

**Issue by JJDelisle** [ConfusedAlex/GoldEconomy#8]
When in game and using the /bank withdraw function, any amount returns "you have withdrawn 0 gold" but still puts the gold in my inventory. this is occurring even to OP. This is problematic for obvious reasons.

**Comment by JJDelisle** [comment]
worth mentioning that the balance also does not change when withdraw states 0

**Comment by ConfusedAlex** [comment]
I'm currently on vacation so I can address this issue only in 1 week.
